config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  unauthenticated(:user) do
    root to: "pages#landing", as: :landing
  end

  authenticated(:user) do
    root to: "games#index"
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")



  resources :pages, only: [:index]
  get '/profile', to: 'pages#profile', as: 'profile'

  resources :pages, only: [:index]
  get '/leaderboard', to: 'pages#leaderboard', as: 'leaderboard'

  resources :pages, only: [:index]
  get '/results', to: 'pages#results', as: 'results'

  resources :pages, only: [:index]
  get '/statistics', to: 'pages#statistics', as: 'statistics'

  resources :pages, only: [:index]
  get '/prizewheel', to: 'pages#prizewheel', as: 'prizewheel'

  resources :questions, only: [:show]
  resources :answers, only: [:show]
  resources :responses, only: [:create]
  resources :games, only: [:index, :show] do
    member do
      get :score
    end
  end
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :questions
  has_many :responses, through: :questions
  has_many :answers, through: :questions
  has_many :game_sessions
  has_many :users, through: :game_sessions

  def played_users
    responses.map(&:user).uniq
  end

  def total_score_for(user)
    responses.where(user: user).sum(:score)
  end

  def self.started_games(user)
    responses = user.responses.all
    unless responses.nil?
      games_responses = responses.map do |response|
        response.question.game
      end
      return games_responses.uniq
    end
  end

  def self.games_in_session(user)
    GameSessions.where(user_id: user.id)
  end

  def self.completed_games(user)
    responses = user.responses.all
    unless responses.nil?
      questions_with_responses = responses.map { |response| response.question }

      games_completed = started_games(user).select do |game|
        game.questions.to_set.subset?(questions_with_responses.to_set)
      end
      return games_completed
    end
  end

end

app/controllers/games_controller.rb
require 'set'

class GamesController < ApplicationController
  def index
    @games = Game.all
    @games_started = Game.started_games(current_user)
    @games_completed = Game.completed_games(current_user)

    @games_in_session = GameSession.where(user_id: current_user.id)

    @user_first_name = current_user.first_name
    @user_last_name = current_user.last_name
    @user_email = current_user.email

    @games_remaining = Game.all - Game.started_games(current_user)

    @users = User.leaderboard_ranked
    @games_count = {}
    @games_count[:all] = Game.all.size
    @games_count[:started] = Game.started_games(current_user).size
    @games_count[:completed] = Game.completed_games(current_user).size


    @games_remaining_count = @games_count[:all] - @games_in_session.count

  end

  def show
    @game = Game.find(params[:id])
    @game_session = GameSession.create(game: @game, user: current_user) if GameSession.find_by(game: @game, user: current_user).nil?
    @users = User.all.first(7) # just for the demo incase other ppl join during presentation
    GameChannel.broadcast_to(
      @game,
      {
        userId: current_user.id,
        name: current_user.first_name
      }
    )
  end

  def score

    sleep(5)
    
    @user_first_name = current_user.first_name

    @game = Game.find(params[:id])
    @total_score = @game.total_score_for(current_user)

    @users = @game.responses.map(&:user).uniq.sort_by do |user|
      -user.game_score(@game)
    end

    GameSession.find_by(game: @game, user: current_user)&.destroy
  end
end

app/views/games/index.html.erb
    <section class="wrapper">
      <section class="summary">

      <% if current_user.full_body.attached? %>
        <section class="profile-head" style="background-image: linear-gradient(180deg, rgba(27,28,30,0) 75%, rgba(27,28,30,.99) 95%), url(<%= cloudinary_url current_user.full_body.key %>)"></section>
      <% else %>
        <%= link_to edit_user_registration_path do %>
          <section class="profile-head" style="background-image: linear-gradient(180deg, rgba(27,28,30,0) 75%, rgba(27,28,30,.99) 95%), url(<%= asset_path 'profile-body-default.png' %>)"></section>
        <% end %>
      <% end %>

        <p>Welcome back <%= current_user.first_name.capitalize %>,</p>
        <h1>You're a Wagon Wheel genius!</h1>
        <ul>
          <li class="current-standing"><span>Current standing</span><strong>1st</strong></li>
          <li class="best-result"><span>Best result</span><strong>1st</strong></li>
          <li class="latest-result"><span>Latest result</span><strong>2nd</strong></li>
        </ul>
        <%= link_to "Join game", game_path(@games.find_by(title: "Programming Basics")), class:"primary button" %>
        <%= link_to "Leaderboard", leaderboard_path, class: "secondary button" %>

      </section>
    </section>

<!--
    <section class="wrapper">

      <section class="title">
        <h3>All games</h3>
        <p><%= @games.count %> games</p>
      </section>

      <section class="games">
        <% @games.each do |game| %>
          <section class="game <%= game.topic.downcase %>">
              <a href="games/<%= game.id %>">
                <%= image_tag "icon-#{game.topic.downcase}.svg", class: "icon" %>
                <h4><%= game.topic %></h4>
                <h5><%= game.title %></h5>
                <span>Play game</span>
              </a>
          </section>
        <% end %>
      </section>

    </section>
-->

    <section class="wrapper">

      <section class="title">
        <h3>Upcoming games</h3>
        <p><%= @games_remaining_count %> games remaining</p>
      </section>

      <section class="games">
        <% @games_remaining.each do |game| %>
          <section class="game <%= game.topic.downcase %>" data-controller="live-subscription" data-live-subscription-game-id-value="<%= game.id %>">
            <% if game.questions.count > 1 %>
              <a href=<%= "games/#{game.id}" %>>
            <% else %>
              <a>
            <% end %>
                <%= image_tag "icon-#{game.topic.downcase}.svg", class: "icon" %>
                <h4><%= game.topic %></h4>
                <h5><%= game.title %></h5>
                <div class="live" data-live-subscription-target="live">
                  <% if game.users.count >= 1 %>
                      <div class="pulse">
                        <div class="default"></div>
                        <div class="transition"></div>
                      </div>
                      <h6>Live</h6>
                  <% end %>
                </div>
                <% if game.questions.count > 1 %>
                  <span>Play game</span>
                <% else %>
                  <span class="disable">Coming soon</span>
                <% end %>
            </a>

            <!--
            <% if game.users.count >= 1 %>
              <a href="games/<%= game.id %>">
                <%= image_tag "icon-#{game.topic.downcase}.svg", class: "icon" %>
                <h4><%= game.topic %></h4>
                <h5><%= game.title %></h5>
                <div class="live">
                  <div class="pulse">
                    <div class="default"></div>
                    <div class="transition"></div>
                  </div>
                  <h6>Live</h6>
                </div>
                <span>Play game</span>
              </a>
            <% elsif game.questions.count > 1 %>
              <a href="games/<%= game.id %>">
                <%= image_tag "icon-#{game.topic.downcase}.svg", class: "icon" %>
                <h4><%= game.topic %></h4>
                <h5><%= game.title %></h5>
                <span>Play game</span>
              </a>
            <% else %>
              <a>
                <%= image_tag "icon-#{game.topic.downcase}.svg", class: "icon" %>
                <h4><%= game.topic %></h4>
                <h5><%= game.title %></h5>
                <span>Coming soon</span>
              </a>
            <% end %>
            -->
          </section>
        <% end %>
      </section>

    </section>

    <section class="wrapper d-none">

      <section class="title">
        <h3>Started games</h3>
        <p><%= @games_in_session.count %> games started</p>
      </section>

      <!--section class="games">
        <% @games_started.each do |game| %>
          <section class="game <%= game.topic.downcase %>">
              <a href="games/<%= game.id %>">
                <%= image_tag "icon-#{game.topic.downcase}.svg", class: "icon" %>
                <h4><%= game.topic %></h4>
                <h5><%= game.title %></h5>

                <section class="users connecting">

                  <% game.users.each do |user| %>
                    <section class="user">
                      <% if user.headshot.attached? %>
                        <%= cl_image_tag user.headshot.key, class: "profile-head-default" %>
                      <% else %>
                        <%= image_tag "profile-head-default.png",class: "profile-head-default" %>
                      <% end %>
                    </section>
                  <% end %>
                </section>

                <span>Continue game</span>
              </a>
          </section>
        <% end %>
      </section-->

      <section class="games">
        <% @games_in_session.each do |game_session| %>
          <section class="game <%= game_session.game.topic.downcase %>">
              <a href="games/<%= game_session.game.id %>">
                <%= image_tag "icon-#{ game_session.game.topic.downcase}.svg", class: "icon" %>
                <h4><%= game_session.game.topic %></h4>
                <h5><%= game_session.game.title %></h5>

                <section class="users connecting">

                  <% game_session.game.users.each do |user| %>
                    <section class="user">
                      <% if user.headshot.attached? %>
                        <%= cl_image_tag user.headshot.key, class: "profile-head-default" %>
                      <% else %>
                        <%= image_tag "profile-head-default.png",class: "profile-head-default" %>
                      <% end %>
                    </section>
                  <% end %>
                </section>

                <span>Continue game</span>
              </a>
          </section>
        <% end %>
      </section>

    </section>

    <section class="wrapper">

      <section class="title">
        <h3>Completed games</h3>
        <p><%= @games_count[:completed] %> games completed</p>
      </section>

      <section class="games">
        <% @games_completed.each do |game| %>
          <section class="game <%= game.topic.downcase %>">
              <a href="results">
                <%= image_tag "icon-#{game.topic.downcase}.svg", class: "icon" %>
                <h4><%= game.topic %></h4>
                <h5><%= game.title %></h5>

                <section class="users connecting">

                <% game.users.each do |user| %>
                    <section class="user">
                      <% if user.headshot.attached? %>
                        <%= cl_image_tag user.headshot.key, class: "profile-head-default" %>
                      <% else %>
                        <%= image_tag "profile-head-default.png",class: "profile-head-default" %>
                      <% end %>
                    </section>
                  <% end %>
                </section>

                <span>Show results</span>
              </a>
          </section>
        <% end %>
      </section>

    </section>

app/views/games/score.html.erb
<h2>Final result</h2>
<% if @total_score == 1 %>
  <p>You answered <%= @total_score %> question correctly.</p>
<% else %>
  <p>You answered <%= @total_score %> questions correctly.</p>
<% end %>

<section class="resultstable" data-controller="score-timer" data-score-timer-current-user-id-value="<%= current_user.id %>" data-score-timer-winner-user-id-value="<%= @users.first.id %>">

  <% @users.each_with_index do |user, index|%>

    <section class="player <%= user == current_user ? 'current'.html_safe : '' %>">
      <section class="player-avatar">

        <% if user.headshot.attached? %>
            <%= cl_image_tag user.headshot.key, data: { user_id: user.id, game_subscription_target: "avatar"}, class: "profile-head-default #{user.first_name}" %>
          <% else %>
            <%= link_to edit_user_registration_path do %>
              <%= image_tag "profile-head-default.png", data: { user_id: user.id, game_subscription_target: "avatar"}, class: "profile-head-default #{user.first_name}" %>
            <% end %>
          <% end %>

          <% if user.full_body.attached? %>
            <%= cl_image_tag user.full_body.key, class: "profile-body-default #{user.first_name}" %>
          <% else %>
            <%= link_to edit_user_registration_path do %>
              <%= image_tag "profile-body-default.png", class: "profile-body-default #{user.first_name}" %>
            <% end %>
          <% end %>

      </section>

      <section class="player-details">
        <section class="player-name"><h4><%= user.first_name %> <%= user == current_user ? '<span>YOU</span>'.html_safe : '' %></h4></section>
      </section>
      <section class="player-points"><%= user.game_score(@game) %> points</section>
      <section class="player-score"><h3></h3></section>
    </section>

  <% end %>

  <section class="winner" data-score-timer-target="resultstable">
    <section class="result">
      <% if @users.first.email == "phillip@gmail.com" %>
        <%= image_tag "phillip-head-party.png", class: "party" %>
      <% else %>
        <% if @users.first.headshot.attached? %>
            <%= cl_image_tag @users.first.headshot.key, data: { user_id: @users.first.id, game_subscription_target: "avatar"}, class: "party #{@users.first.first_name}" %>
        <% else %>
          <%= link_to edit_user_registration_path do %>
            <%= image_tag "profile-head-default.png", data: { user_id: @users.first.id, game_subscription_target: "avatar"}, class: "party #{@users.first.first_name}" %>
          <% end %>
        <% end %>
      <% end%>
      <span class="won">You won!</span>
      <p>Well done <%= @users.first.first_name %>. You mastered <%= @game.topic %>, <%= @game.title %>. It's now time to collect your prize!</p>
    </section>
  </section>

</section>

app/views/games/show.html.erb
<div data-controller="game-subscription" data-game-subscription-game-id-value="<%= @game.id %>">
    <h2>Hang Tight!</h2>
    <p>Your friends are connecting in. The game will commence shortly.</p>

    <section class="users">
      <% @users.each do |user| %>
        <section class="user <%= 'connected' if (user.id == current_user.id) || (@game.users.include? user) %>"
          data-game-subscription-target="avatarContainer" data-user-id=<%= user.id %>>
          <% if user.headshot.attached? %>
            <%= cl_image_tag user.headshot.key, data: { user_id: user.id, game_subscription_target: "avatar"}, class: "profile-head-default #{user.first_name}" %>
          <% else %>
            <%= link_to edit_user_registration_path do %>
              <%= image_tag "profile-head-default.png", data: { user_id: user.id, game_subscription_target: "avatar"}, class: "profile-head-default #{user.first_name}" %>
            <% end %>
          <% end %>
          <%= image_tag "icon-tick.svg", class: "tick" %>
          <span><%= user.first_name %></span>
        </section>
      <% end %>
  </section>

  <section class="actions <%= "d-none" unless current_user == User.find_by(email: "phillip@gmail.com") %>">
    <%= link_to "Start game", question_url(@game.questions.find_by(order: 1)), class: "primary button", data: { game_subscription_target: "start" } %>
  </section>
</div>